[package]
name = "lg-webos-client"
version = "0.2.0"
authors = ["kasper.ziemianek@gmail.com"]
edition = "2018"
description = "LG webOS client"
readme = "README.md"
repository = "https://github.com/kziemianek/lg-webos-client"
license-file = "LICENSE"
keywords = ["lg", "webos", "bindings"]

[dependencies]
tokio-tungstenite = "0.14.0"
futures-util = "0.3"
tokio = { version = "1.2.0", default-features = false, features = ["rt"] }
url = "2.1.0"
serde_json = "1.0"
serde = { version = "1.0.123", features = ["derive"]}
pinky-swear = "5.1.0"